/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nlmcbk-xdr.h"

bool_t
xdr_nlm_sm_status (XDR *xdrs, nlm_sm_status *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_string (xdrs, &objp->mon_name, LM_MAXSTRLEN))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->priv, 16))
		 return FALSE;
	return TRUE;
}
